import { access, readdir, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { Pool } from 'pg';
import { z } from 'zod';
import type { AICoachContext, AICoachPatchContext, PatchChampionUpdate, PatchSystemUpdate } from './aiCoachSchemas.js';
import { env } from '../config/env.js';
import { ensureWrite } from '../utils/fs.js';

const patchNotesDir = fileURLToPath(new URL('../../data/patch-notes', import.meta.url));
const pool = env.DATABASE_URL ? new Pool({ connectionString: env.DATABASE_URL }) : null;
let tableReady: Promise<void> | null = null;
let syncPromise: Promise<PatchNotesFile | null> | null = null;
let lastSyncAttemptAt = 0;

const championUpdateSchema = z.object({
  championName: z.string().min(1),
  changeType: z.enum(['buff', 'nerf', 'adjustment', 'rework']),
  roles: z.array(z.string().min(1)).min(1),
  summary: z.string().min(1),
  impactLevel: z.enum(['low', 'medium', 'high'])
});

const systemUpdateSchema = z.object({
  category: z.string().min(1),
  summary: z.string().min(1),
  impactLevel: z.enum(['low', 'medium', 'high'])
});

const patchNotesSchema = z.object({
  patch: z.string().min(1),
  publishedAt: z.string().min(1),
  sourceUrl: z.string().url(),
  summary: z.array(z.string().min(1)).min(1),
  championUpdates: z.array(championUpdateSchema).default([]),
  systemUpdates: z.array(systemUpdateSchema).default([]),
  rawText: z.string().optional(),
  detectedAt: z.string().optional(),
  autoGenerated: z.boolean().optional()
});

type PatchNotesFile = z.infer<typeof patchNotesSchema>;

type LatestPatchEntry = {
  patch: string;
  publishedAt: string;
  teaser: string;
  sourceUrl: string;
};

const championRoleMap: Record<string, string[]> = {
  ahri: ['MIDDLE'],
  azir: ['MIDDLE'],
  cassiopeia: ['MIDDLE'],
  graves: ['JUNGLE'],
  kalista: ['BOTTOM'],
  karma: ['UTILITY', 'MIDDLE'],
  lissandra: ['MIDDLE'],
  nami: ['UTILITY'],
  ornn: ['TOP'],
  pyke: ['UTILITY'],
  rell: ['UTILITY', 'JUNGLE'],
  shen: ['TOP'],
  shyvana: ['JUNGLE', 'TOP']
};

function parsePatchParts(patch?: string | null) {
  if (!patch) return null;
  const match = patch.match(/(\d+)\.(\d+)/);
  if (!match) return null;

  return {
    major: Number(match[1]),
    minor: Number(match[2])
  };
}

function comparePatch(left?: string | null, right?: string | null) {
  const a = parsePatchParts(left);
  const b = parsePatchParts(right);
  if (!a || !b) return 0;
  if (a.major !== b.major) return a.major - b.major;
  return a.minor - b.minor;
}

function normalizeChampionName(name?: string | null) {
  return name?.trim().toLowerCase() ?? '';
}

function decodeHtmlEntities(input: string) {
  return input
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)))
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#x27;/g, "'")
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&nbsp;/g, ' ');
}

function htmlToText(html: string) {
  return decodeHtmlEntities(
    html
      .replace(/<script[\s\S]*?<\/script>/gi, ' ')
      .replace(/<style[\s\S]*?<\/style>/gi, ' ')
      .replace(/<noscript[\s\S]*?<\/noscript>/gi, ' ')
      .replace(/<\/(p|div|section|article|header|footer|h1|h2|h3|h4|li|ul|ol|br)>/gi, '\n')
      .replace(/<[^>]+>/g, ' ')
  )
    .replace(/\r/g, '')
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function toLines(text: string) {
  return text
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => !line.startsWith('Image'));
}

function inferChampionRoles(championName: string) {
  return championRoleMap[normalizeChampionName(championName)] ?? ['ALL'];
}

function inferChangeType(snippet: string): PatchChampionUpdate['changeType'] {
  const lower = snippet.toLowerCase();
  if (lower.includes('rework') || lower.includes('major update') || lower.includes('brand new model') || lower.includes('new update')) return 'rework';
  if (lower.includes('nerf') || lower.includes('weaker') || lower.includes('reduce') || lower.includes('reduced')) return 'nerf';
  if (lower.includes('buff') || lower.includes('stronger') || lower.includes('improve') || lower.includes('increased')) return 'buff';
  return 'adjustment';
}

function inferImpactLevel(snippet: string, changeType: PatchChampionUpdate['changeType']): PatchChampionUpdate['impactLevel'] {
  const lower = snippet.toLowerCase();
  if (changeType === 'rework') return 'high';
  if (lower.includes('major') || lower.includes('significant') || lower.includes('full update')) return 'high';
  if (lower.includes('small') || lower.includes('minor')) return 'low';
  return 'medium';
}

function isLikelyHeading(line: string) {
  if (line.length > 28) return false;
  if (/\d/.test(line)) return false;
  if (line.includes(':')) return false;
  if (line.includes('Patch') || line.includes('Game Updates') || line.includes('Bugfix') || line.includes('Upcoming')) return false;
  return /^[A-Z][A-Za-z' .-]+$/.test(line);
}

function sentenceClip(input: string, maxLength = 220) {
  const sentence = input.split(/(?<=[.!?])\s+/)[0] ?? input;
  return sentence.length <= maxLength ? sentence : `${sentence.slice(0, maxLength - 1).trim()}…`;
}

function extractIntroSummary(lines: string[], title: string, teaser: string) {
  const titleIndex = lines.findIndex((line) => line.includes(title));
  const startIndex = titleIndex >= 0 ? titleIndex + 1 : 0;
  const collected: string[] = [];

  for (let index = startIndex; index < lines.length; index += 1) {
    const line = lines[index];
    if (line === 'Patch Highlights' || line === 'Champions' || line === 'Systems') break;
    if (line.length < 35) continue;
    if (line.startsWith('Riot ')) continue;
    if (/^\d{4}-\d{2}-\d{2}/.test(line)) continue;
    collected.push(sentenceClip(line));
    if (collected.length >= 2) break;
  }

  return [sentenceClip(teaser), ...collected].filter((value, index, array) => value && array.indexOf(value) === index).slice(0, 3);
}

function extractChampionUpdates(lines: string[]) {
  const updates: PatchChampionUpdate[] = [];
  const systemsIndex = lines.findIndex((line) => line === 'Systems');

  for (let index = 0; index < lines.length; index += 1) {
    const heading = lines[index];
    if (!isLikelyHeading(heading)) continue;
    if (systemsIndex !== -1 && index >= systemsIndex) break;

    const nextLine = lines[index + 1] ?? '';
    if (nextLine.length < 25) continue;

    const changeType = inferChangeType(nextLine);
    if (changeType === 'adjustment' && !nextLine.toLowerCase().includes(heading.toLowerCase())) continue;

    updates.push({
      championName: heading,
      changeType,
      roles: inferChampionRoles(heading),
      summary: sentenceClip(nextLine),
      impactLevel: inferImpactLevel(nextLine, changeType)
    });
  }

  return updates.filter((update, index, array) => array.findIndex((entry) => entry.championName === update.championName) === index);
}

function extractSystemUpdates(lines: string[]) {
  const systemsIndex = lines.findIndex((line) => line === 'Systems');
  if (systemsIndex === -1) return [];

  const updates: PatchSystemUpdate[] = [];
  for (let index = systemsIndex + 1; index < lines.length; index += 1) {
    const line = lines[index];
    if (line.startsWith('Summoner')) break;
    if (line.startsWith('Arena')) break;
    if (line.startsWith('Bugfix')) break;
    if (line.startsWith('Upcoming')) break;

    const nextLine = lines[index + 1] ?? '';
    if (!line || nextLine.length < 25) continue;

    const isCategory = /^[A-Z0-9][A-Z0-9 ':-]+$/.test(line) || isLikelyHeading(line);
    if (!isCategory) continue;

    updates.push({
      category: line.toLowerCase().replace(/\s+/g, '_'),
      summary: sentenceClip(nextLine),
      impactLevel: nextLine.toLowerCase().includes('major') ? 'high' : 'medium'
    });
  }

  return updates.filter((update, index, array) => array.findIndex((entry) => entry.category === update.category) === index).slice(0, 4);
}

function extractChampionSnippetsFromRawText(rawText: string, championNames: string[]) {
  const lines = toLines(rawText);

  return championNames.flatMap((championName) => {
    const index = lines.findIndex((line) => normalizeChampionName(line) === normalizeChampionName(championName));
    if (index === -1) return [];

    const snippet = sentenceClip(lines.slice(index + 1, index + 3).join(' '));
    if (!snippet) return [];

    const changeType = inferChangeType(snippet);
    return [{
      championName,
      changeType,
      roles: inferChampionRoles(championName),
      summary: snippet,
      impactLevel: inferImpactLevel(snippet, changeType)
    } satisfies PatchChampionUpdate];
  });
}

function extractSystemSnippetsFromRawText(rawText: string, context: Omit<AICoachContext, 'patchContext'>) {
  const lines = toLines(rawText);
  const role = context.player.roleFilter.toLowerCase();
  const keywords = role === 'jungle'
    ? ['jungle', 'objective', 'monster']
    : role === 'middle'
      ? ['mid', 'objective', 'roam']
      : role === 'top'
        ? ['top', 'side', 'objective']
        : role === 'bottom' || role === 'utility'
          ? ['support', 'bot', 'objective']
          : ['objective', 'vision', 'lane'];

  return lines
    .filter((line) => keywords.some((keyword) => line.toLowerCase().includes(keyword)))
    .slice(0, 2)
    .map((line, index) => ({
      category: `auto_${index + 1}`,
      summary: sentenceClip(line),
      impactLevel: 'medium' as const
    }));
}

async function ensureTables() {
  if (!pool) return;
  if (!tableReady) {
    tableReady = pool.query(`
      CREATE TABLE IF NOT EXISTS patch_notes_cache (
        patch TEXT PRIMARY KEY,
        payload JSONB NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `).then(() => undefined);
  }

  await tableReady;
}

async function loadStoredPatchNotes() {
  if (!pool) return [] as PatchNotesFile[];
  await ensureTables();
  const result = await pool.query<{ payload: PatchNotesFile }>(`SELECT payload FROM patch_notes_cache`);
  return result.rows.map((row) => patchNotesSchema.parse(row.payload));
}

async function savePatchNotes(note: PatchNotesFile) {
  if (pool) {
    await ensureTables();
    await pool.query(
      `INSERT INTO patch_notes_cache (patch, payload, updated_at)
       VALUES ($1, $2::jsonb, NOW())
       ON CONFLICT (patch) DO UPDATE SET payload = EXCLUDED.payload, updated_at = NOW()`,
      [note.patch, JSON.stringify(note)]
    );
    return;
  }

  await ensureWrite(`${patchNotesDir}/${note.patch}.auto.json`, `${JSON.stringify(note, null, 2)}\n`);
}

async function loadLocalPatchNotes() {
  try {
    const entries = await readdir(patchNotesDir, { withFileTypes: true });
    const files = entries.filter((entry) => entry.isFile() && entry.name.endsWith('.json'));

    const notes = await Promise.all(files.map(async (entry) => {
      const raw = await readFile(`${patchNotesDir}/${entry.name}`, 'utf8');
      return patchNotesSchema.parse(JSON.parse(raw));
    }));

    return notes;
  } catch (error) {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT') return [];
    throw error;
  }
}

async function patchNoteExistsOnDisk(patch: string) {
  try {
    await access(`${patchNotesDir}/${patch}.json`);
    return true;
  } catch {
    try {
      await access(`${patchNotesDir}/${patch}.auto.json`);
      return true;
    } catch {
      return false;
    }
  }
}

async function fetchText(url: string) {
  const response = await fetch(url, {
    headers: {
      'user-agent': 'Don-Sosa-Coach/1.0'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status}`);
  }

  return response.text();
}

function parseLatestPatchEntryFromTagPage(html: string): LatestPatchEntry | null {
  const text = htmlToText(html);
  const match = text.match(/Game Updates\s+(\d{4}-\d{2}-\d{2}T[^\s]+)\s+(?:League of Legends\s+)?Patch\s+(\d+\.\d+)\s+Notes\s+(.+?)(?=Game Updates\s+\d{4}-\d{2}-\d{2}T|SHOW MORE|$)/s);
  if (!match) return null;

  const [, publishedAt, patch, teaser] = match;
  return {
    patch,
    publishedAt,
    teaser: teaser.trim(),
    sourceUrl: `https://www.leagueoflegends.com/en-us/news/game-updates/league-of-legends-patch-${patch}-notes/`
  };
}

function buildAutoPatchNote(entry: LatestPatchEntry, articleHtml: string): PatchNotesFile {
  const rawText = htmlToText(articleHtml);
  const lines = toLines(rawText);
  const title = `Patch ${entry.patch} Notes`;

  return patchNotesSchema.parse({
    patch: entry.patch,
    publishedAt: entry.publishedAt,
    sourceUrl: entry.sourceUrl,
    summary: extractIntroSummary(lines, title, entry.teaser),
    championUpdates: extractChampionUpdates(lines),
    systemUpdates: extractSystemUpdates(lines),
    rawText,
    detectedAt: new Date().toISOString(),
    autoGenerated: true
  });
}

function isRelevantChampion(update: PatchChampionUpdate, names: string[]) {
  const target = normalizeChampionName(update.championName);
  return names.some((name) => normalizeChampionName(name) === target);
}

function isRelevantSystem(update: PatchSystemUpdate, context: Omit<AICoachContext, 'patchContext'>) {
  const role = context.player.roleFilter.toLowerCase();
  const haystack = `${update.category} ${update.summary}`.toLowerCase();

  if (role === 'jungle') return haystack.includes('jungle') || haystack.includes('objective');
  if (role === 'middle') return haystack.includes('mid') || haystack.includes('roam') || haystack.includes('objective');
  if (role === 'top') return haystack.includes('top') || haystack.includes('side') || haystack.includes('objective');
  if (role === 'bottom' || role === 'utility') return haystack.includes('bot') || haystack.includes('support') || haystack.includes('objective');
  return haystack.includes('objective') || haystack.includes('lane') || haystack.includes('vision');
}

function localizeChampionUpdate(update: PatchChampionUpdate, locale: 'es' | 'en', patch: string): PatchChampionUpdate {
  if (locale === 'en') return update;

  const changeTypeText = update.changeType === 'buff'
    ? 'un buff'
    : update.changeType === 'nerf'
      ? 'un nerf'
      : update.changeType === 'rework'
        ? 'una rework fuerte'
        : 'ajustes';
  const impactText = update.impactLevel === 'high'
    ? 'de impacto alto'
    : update.impactLevel === 'low'
      ? 'de impacto bajo'
      : 'de impacto medio';

  return {
    ...update,
    summary: `${update.championName} recibió ${changeTypeText} ${impactText} en el parche ${patch}.`
  };
}

function localizeSystemUpdate(update: PatchSystemUpdate, locale: 'es' | 'en', patch: string): PatchSystemUpdate {
  if (locale === 'en') return update;

  const categoryLabel = update.category.replace(/_/g, ' ');
  const impactText = update.impactLevel === 'high'
    ? 'impacto alto'
    : update.impactLevel === 'low'
      ? 'impacto bajo'
      : 'impacto medio';

  return {
    ...update,
    summary: `Se detectó una actualización sistémica vinculada a ${categoryLabel} con ${impactText} en el parche ${patch}.`
  };
}

function buildLocalizedPatchSummary(currentNotes: PatchNotesFile, context: Omit<AICoachContext, 'patchContext'>, relevantChampionUpdates: PatchChampionUpdate[], relevantSystemUpdates: PatchSystemUpdate[]) {
  if (context.player.locale === 'en') {
    return currentNotes.summary.slice(0, 3);
  }

  const lines = [
    `El parche ${currentNotes.patch} es el contexto live que usa el coaching por defecto.`,
    relevantChampionUpdates.length
      ? `Se detectaron cambios recientes sobre ${relevantChampionUpdates.map((update) => update.championName).join(', ')}.`
      : `No se detectaron cambios directos sobre tu pool principal dentro de este parche.`,
    relevantSystemUpdates.length
      ? `También hay ajustes sistémicos que pueden afectar tu contexto actual.`
      : `En este bloque sigue pesando más el conocimiento evergreen que un cambio sistémico puntual.`
  ];

  return lines.slice(0, 3);
}

function syncIntervalMs() {
  return Math.max(1, env.PATCH_NOTES_SYNC_INTERVAL_HOURS) * 60 * 60 * 1000;
}

export async function loadPatchNotes() {
  const [localNotes, storedNotes] = await Promise.all([loadLocalPatchNotes(), loadStoredPatchNotes()]);
  const deduped = new Map<string, PatchNotesFile>();

  for (const note of [...localNotes, ...storedNotes]) {
    const existing = deduped.get(note.patch);
    if (!existing || (note.detectedAt && !existing.detectedAt)) {
      deduped.set(note.patch, note);
    }
  }

  return Array.from(deduped.values()).sort((a, b) => comparePatch(b.patch, a.patch));
}

export async function refreshPatchNotesFromOfficialSource(force = false) {
  if (!env.PATCH_NOTES_AUTO_SYNC && !force) return null;
  if (!force && Date.now() - lastSyncAttemptAt < syncIntervalMs()) return null;
  if (syncPromise) return syncPromise;

  lastSyncAttemptAt = Date.now();
  syncPromise = (async () => {
    const tagHtml = await fetchText(env.PATCH_NOTES_TAG_URL);
    const latest = parseLatestPatchEntryFromTagPage(tagHtml);
    if (!latest) return null;

    const knownNotes = await loadPatchNotes();
    const existing = knownNotes.find((note) => comparePatch(note.patch, latest.patch) === 0);
    if (existing && !force) return existing;

    const articleHtml = await fetchText(latest.sourceUrl);
    const note = buildAutoPatchNote(latest, articleHtml);
    await savePatchNotes(note);
    return note;
  })()
    .catch((error) => {
      console.error('Patch notes auto-sync failed:', error);
      return null;
    })
    .finally(() => {
      syncPromise = null;
    });

  return syncPromise;
}

export async function getCurrentPatchNotes() {
  await refreshPatchNotesFromOfficialSource(false);

  const notes = await loadPatchNotes();
  if (!notes.length) return null;

  if (env.CURRENT_LOL_PATCH) {
    return notes.find((note) => comparePatch(note.patch, env.CURRENT_LOL_PATCH) === 0) ?? notes[0];
  }

  return notes[0];
}

export async function getPatchContextForCoach(context: Omit<AICoachContext, 'patchContext'>): Promise<AICoachPatchContext> {
  const currentNotes = await getCurrentPatchNotes();

  if (!currentNotes) {
    return {
      currentPatch: env.CURRENT_LOL_PATCH ?? 'unknown',
      sourceUrl: env.PATCH_NOTES_TAG_URL,
      summary: [],
      relevantChampionUpdates: [],
      relevantSystemUpdates: [],
      note: context.player.locale === 'en'
        ? 'No patch note dataset is loaded yet.'
        : 'Todavía no hay un dataset de patch notes cargado.'
    };
  }

  const trackedChampions = [
    context.player.anchorChampion,
    ...context.championPool.slice(0, 3).map((champion) => champion.championName),
    context.matchupAlert?.opponentChampionName ?? null
  ].filter(Boolean) as string[];

  const explicitChampionUpdates = currentNotes.championUpdates.filter((update) => isRelevantChampion(update, trackedChampions));
  const fallbackChampionUpdates = currentNotes.rawText
    ? extractChampionSnippetsFromRawText(currentNotes.rawText, trackedChampions)
    : [];
  const relevantChampionUpdates = [...explicitChampionUpdates, ...fallbackChampionUpdates]
    .filter((update, index, array) => array.findIndex((entry) => normalizeChampionName(entry.championName) === normalizeChampionName(update.championName)) === index)
    .slice(0, 3)
    .map((update) => localizeChampionUpdate(update, context.player.locale, currentNotes.patch));

  const explicitSystemUpdates = currentNotes.systemUpdates.filter((update) => isRelevantSystem(update, context));
  const fallbackSystemUpdates = currentNotes.rawText
    ? extractSystemSnippetsFromRawText(currentNotes.rawText, context)
    : [];
  const relevantSystemUpdates = [...explicitSystemUpdates, ...fallbackSystemUpdates]
    .filter((update, index, array) => array.findIndex((entry) => entry.category === update.category && entry.summary === update.summary) === index)
    .slice(0, 2)
    .map((update) => localizeSystemUpdate(update, context.player.locale, currentNotes.patch));

  return {
    currentPatch: currentNotes.patch,
    sourceUrl: currentNotes.sourceUrl,
    summary: buildLocalizedPatchSummary(currentNotes, context, relevantChampionUpdates, relevantSystemUpdates),
    relevantChampionUpdates,
    relevantSystemUpdates,
    note: context.player.locale === 'en'
      ? `Patch context auto-syncs from official Riot patch notes. If your pool or matchup was touched recently, the coaching will adjust emphasis automatically.`
      : `El contexto de parche se sincroniza automáticamente desde las patch notes oficiales de Riot. Si tu pool o matchup fue tocado recientemente, el coaching ajusta el énfasis de forma automática.`
  };
}
